### ISSUE TITLE
RSSI limit has no effect in paxcounter

### ISSUE THREAD

**Issue by wally2511** [dbSuS/libpax#10]
RSSI limit has no effect, I tried values from -40 to -110 but it didn't change the number of bluetooth devices detected. Set logging to DEBUG and I could see the MACs and their RSSI but the paxcounter still reported the devices above the RSSI limit value. The RSSI value is reporting correct on the OLED display which indicates that remote command has been successful.

**Comment by cyberman54** [comment]
You are right. The rssi filter function has not yet been implemented in this library. Can you suggest a PR, maybe?

**Comment by wally2511** [comment]
I'm sorry, what do you mean by PR?

**Comment by wally2511** [comment]
@cyberman54 I'll have a look but I'm new to paxcounter and am still getting my head around it.

**Comment by wally2511** [comment]
I had a look today but it's going to be above my skillset to put together a PR, sorry.

**Comment by cyberman54** [comment]
Solved with https://github.com/dbSuS/libpax/pull/3
