### ISSUE TITLE
Program size is greater than maximum allowed.

### ISSUE THREAD

**Issue by Eldoprano** [dbSuS/libpax#11]
I was trying to build the latest version of https://github.com/cyberman54/libpax/ on my LoPy4 , and I got the following error message:
`fatal error: esp_bt.h: No such file or directory`
I was able to fix this by adding Bluetooth with the command
`pio run -t menuconfig` And then `Component config` -> `Bluetooth`

But now I run into a problem that I think was already fixed in [this issue](https://github.com/cyberman54/ESP32-Paxcounter/issues/479) from the PaxCounter project.
The error says:
```Linking .pio\build\espidf\firmware.elf
Retrieving maximum program size .pio\build\espidf\firmware.elf
Checking size .pio\build\espidf\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
Error: The program size (1231913 bytes) is greater than maximum allowed (1048576 bytes)
RAM:   [          ]   4.3% (used 56756 bytes from 1310720 bytes)
*** [checkprogsize] Explicit exit, status 1
Flash: [==========]  117.5% (used 1231913 bytes from 1048576 bytes)
======================================================= [FAILED] Took 484.89 seconds =======================================================
```
I tried to solve this by adding this to the platformio.ini file:
```
[platformio]
default_envs = espidf
board_build.partitions = min_spiffs.csv    <- what I added

[env]
board = lopy4
```
but I get exactly the same error message.

I'm using VSCode, in Windows10

**Comment by FlorianLudwig** [comment]
Hi @Eldoprano ,

the issue is, that the software is to big for the partition on which you want to flash it.

You got a few options:

1. create a bigger partition
2. remove unused software from the project (in menuconfig you can disable stuff you do not use)

Please note, this project is meant to be used as a library, not as a ready-to-go software. You have to write software around the lib to do anything useful. If you are looking for a software to flash on your lopy, you are better served by using: https://github.com/cyberman54/ESP32-Paxcounter

**Comment by Eldoprano** [comment]
Thanks for the response!
My solution didn't worked, because PlatformIO couldn't find the `min_spiffs.csv` and just used the default file with 1MB without telling me.

I solved it now by adding a new file `my_partition_table.csv` to the main directory of the project, with this content:
```
# Name,   Type, SubType, Offset,  Size, Flags
# Note: if you have increased the bootloader size, make sure to update the offsets to avoid overlap
nvs,      data, nvs,     ,        0x6000,
phy_init, data, phy,     ,        0x1000,
factory,  app,  factory, ,        3M,
```
Then changed the variable from my last solution to:
`board_build.partitions = my_partition_table.csv`
And also put that name on the `pio run -t menuconfig` configuration thing.
Now it builds ^^
