### ISSUE TITLE
static wifi_country_t wifi_country = EU is not a valid any more  

### ISSUE THREAD

**Issue by hansju-11** [dbSuS/libpax#19]
in wifiscan.cpp line 45 ff 
static wifi_country_t wifi_country = {"EU", 1,
                                      WIFI_CHANNEL_MAX, 100,
                                      WIFI_COUNTRY_POLICY_MANUAL};

you use EU as a country code.  If you do not change this to eg "DE" or use "EU" in setup, the check in line 105 

  ESP_ERROR_CHECK(
      esp_wifi_set_country(&wifi_country));  // set locales for RF and channels

will fail.
according https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html  (read at 09.10.2022)

Chapter 6. Supported country codes are “01”(world safe mode) “AT”,”AU”,”BE”,”BG”,”BR”, “CA”,”CH”,”CN”,”CY”,”CZ”,”DE”,”DK”,”EE”,”ES”,”FI”,”FR”,”GB”,”GR”,”HK”,”HR”,”HU”, “IE”,”IN”,”IS”,”IT”,”JP”,”KR”,”LI”,”LT”,”LU”,”LV”,”MT”,”MX”,”NL”,”NO”,”NZ”,”PL”,”PT”, “RO”,”SE”,”SI”,”SK”,”TW”,”US”

EU is not allowed any more.

In paxcounter V3.3.2 I got the error:
---
[ 10540][I][main.cpp:289] setup(): [src/main.cpp] BLESCAN: on
ESP_ERROR_CHECK failed: esp_err_t 0x102 (ESP_ERR_INVALID_ARG) at 0x40096120
file: ".pio/libdeps/usb/libpax/lib/libpax/wifiscan.cpp" line 106
func: void wifi_sniffer_init(uint16_t)
expression: esp_wifi_set_country(&wifi_country)
----

I use a old ttgo Lora32 V1 board. (halfile = ttgov1.h)

**Comment by cyberman54** [comment]
@hansju-11 Thanks for spotting this. The issue comes up with Arduino ESP32 v2.05. Thus, easiest way is to use v2.04, while the issue is not yet fixed in the libpax library.

As maintainer of paxcounter i downgraded paxcounter app to v2.04 today. Use `platform_espressif32 = espressif32@5.1.0` in platformio.ini to enforce this.

**Comment by cyberman54** [comment]
@hansju-11 i filed a fix for this issue, will push this as pull request after unit tests are completed successfully.
You can try it by changing the source of libpax in your platformio.ini to this one:
https://github.com/cyberman54/libpax

**Comment by hansju-11** [comment]
Hello Verkehrsrot,I will do the test on the weekend. Thank you.--Diese Nachricht wurde von meinem Mobiltelefon gesendet.Am 19.10.22, 18:38 schrieb Verkehrsrot ***@***.***>:

   
  @hansju-11 i filed a fix for this issue, will push this as pull request after unit tests are completed successfully. You can try it by changing the source of libpax in your platformio.ini to this one: https://github.com/cyberman54/libpax

**Comment by hansju-11** [comment]
Hello Verkehrsrot,

 

the fix works well on my TTG Lora32 V1 Board.

Thanks for the patch.

 

 
 

Gesendet: Mittwoch, 19. Oktober 2022 um 18:38 Uhr
Von: "Verkehrsrot" ***@***.***>
An: "dbSuS/libpax" ***@***.***>
Cc: "hansju-11" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [dbSuS/libpax] static wifi_country_t wifi_country = EU is not a valid any more (Issue #19)


 

@hansju-11 i filed a fix for this issue, will push this as pull request after unit tests are completed successfully.
You can try it by changing the source of libpax in your platformio.ini to this one:
https://github.com/cyberman54/libpax

**Comment by cyberman54** [comment]
This issue can be closed, since it was solved with release 1.1.0

**Comment by hansju-11** [comment]
perfect, works for me
