### ISSUE TITLE
release to platformio registry

### ISSUE THREAD

**Issue by FlorianLudwig** [dbSuS/libpax#9]
To be able to use libpax directly from platformio as `libpax` in the dependencies we should release it to the platformio registry. This would also make the header search work - which would be expected by platformio users, see https://github.com/cyberman54/ESP32-Paxcounter/issues/810

**Comment by cyberman54** [comment]
@FlorianLudwig We need a `pio package publish` here.

**Comment by cyberman54** [comment]
libpax is now preset in platformio's library repository, but i'm still facing a problem with it:

**Comment by cyberman54** [comment]
A `pio package publish` is necessary to register this lib for platformio.
/cc @oliverbrandmueller @FlorianLudwig

**Comment by cyberman54** [comment]
Done.
